In [12]:
import os
import pandas as pd
import datetime as dt

In [15]:
input_data_path = '../data'
input_data_filename = 'binance_BTCUSDT_15m_from_2020_01_01_to_2021_12_31_candlesticks_signals_processed_technical_indicators_and_crypto_index'
input_data_extension = ".csv"
full_path_input_data = os.path.join(input_data_path, input_data_filename + input_data_extension)

In [16]:
df = pd.read_csv(full_path_input_data)

In [17]:
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volumne,number_of_trades,taker_buy_base_asset_volume,...,BBANDS_L,AD,ATR,HT_DC,SAR,ratio_high_open,ratio_low_open,ratio_close_open,time_to_chart_return,crypto_index
0,1577944800000,7138.93,7144.98,7135.00,7138.90,154.330095,1577945699999,1.101881e+06,1732,72.727343,...,7119.218729,-171.772047,16.210334,25.653704,7148.920000,1.000847,0.999449,0.999996,-0.000004,999.995798
1,1577945700000,7138.90,7149.00,7138.50,7146.58,178.369024,1577946599999,1.274135e+06,1738,112.015625,...,7120.381609,-75.622649,15.802453,27.065789,7116.700000,1.001415,0.999944,1.001076,0.001076,1001.071589
2,1577946600000,7145.96,7149.02,7136.41,7136.81,142.773244,1577947499999,1.019787e+06,1650,39.684349,...,7121.342427,-209.338114,15.574421,27.707202,7117.346000,1.000428,0.998664,0.998720,-0.001367,999.703037
3,1577947500000,7136.42,7139.14,7121.43,7135.97,212.128302,1577948399999,1.512872e+06,2549,102.014173,...,7124.153285,-73.149588,15.726962,27.658012,7118.612960,1.000381,0.997900,0.999937,-0.000118,999.585372
4,1577948400000,7136.04,7140.63,7121.01,7125.26,243.045551,1577949299999,1.732451e+06,2848,106.292568,...,7121.926890,-210.900175,16.005036,27.255142,7119.829242,1.000643,0.997894,0.998489,-0.001501,998.085147

In [18]:
df['datetime'] = df.open_time.apply(lambda x: dt.datetime.fromtimestamp(x / 1000.0))

In [19]:
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volumne,number_of_trades,taker_buy_base_asset_volume,...,AD,ATR,HT_DC,SAR,ratio_high_open,ratio_low_open,ratio_close_open,time_to_chart_return,crypto_index,datetime
0,1577944800000,7138.93,7144.98,7135.00,7138.90,154.330095,1577945699999,1.101881e+06,1732,72.727343,...,-171.772047,16.210334,25.653704,7148.920000,1.000847,0.999449,0.999996,-0.000004,999.995798,2020-01-02 07:00:00
1,1577945700000,7138.90,7149.00,7138.50,7146.58,178.369024,1577946599999,1.274135e+06,1738,112.015625,...,-75.622649,15.802453,27.065789,7116.700000,1.001415,0.999944,1.001076,0.001076,1001.071589,2020-01-02 07:15:00
2,1577946600000,7145.96,7149.02,7136.41,7136.81,142.773244,1577947499999,1.019787e+06,1650,39.684349,...,-209.338114,15.574421,27.707202,7117.346000,1.000428,0.998664,0.998720,-0.001367,999.703037,2020-01-02 07:30:00
3,1577947500000,7136.42,7139.14,7121.43,7135.97,212.128302,1577948399999,1.512872e+06,2549,102.014173,...,-73.149588,15.726962,27.658012,7118.612960,1.000381,0.997900,0.999937,-0.000118,999.585372,2020-01-02 07:45:00
4,1577948400000,7136.04,7140.63,7121.01,7125.26,243.045551,1577949299999,1.732451e+06,2848,106.292568,...,-210.900175,16.005036,27.255142,7119.829242,1.000643,0.997894,0.998489,-0.001501,998.085147,2020-01-02 08:00:00

In [20]:
date_value = df['datetime'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S'))
df.insert(0, 'time', date_value)

In [21]:
df.head()

,time,open_time,open,high,low,close,volume,close_time,quote_asset_volumne,number_of_trades,...,AD,ATR,HT_DC,SAR,ratio_high_open,ratio_low_open,ratio_close_open,time_to_chart_return,crypto_index,datetime
0,2020-01-02 07:00:00,1577944800000,7138.93,7144.98,7135.00,7138.90,154.330095,1577945699999,1.101881e+06,1732,...,-171.772047,16.210334,25.653704,7148.920000,1.000847,0.999449,0.999996,-0.000004,999.995798,2020-01-02 07:00:00
1,2020-01-02 07:15:00,1577945700000,7138.90,7149.00,7138.50,7146.58,178.369024,1577946599999,1.274135e+06,1738,...,-75.622649,15.802453,27.065789,7116.700000,1.001415,0.999944,1.001076,0.001076,1001.071589,2020-01-02 07:15:00
2,2020-01-02 07:30:00,1577946600000,7145.96,7149.02,7136.41,7136.81,142.773244,1577947499999,1.019787e+06,1650,...,-209.338114,15.574421,27.707202,7117.346000,1.000428,0.998664,0.998720,-0.001367,999.703037,2020-01-02 07:30:00
3,2020-01-02 07:45:00,1577947500000,7136.42,7139.14,7121.43,7135.97,212.128302,1577948399999,1.512872e+06,2549,...,-73.149588,15.726962,27.658012,7118.612960,1.000381,0.997900,0.999937,-0.000118,999.585372,2020-01-02 07:45:00
4,2020-01-02 08:00:00,1577948400000,7136.04,7140.63,7121.01,7125.26,243.045551,1577949299999,1.732451e+06,2848,...,-210.900175,16.005036,27.255142,7119.829242,1.000643,0.997894,0.998489,-0.001501,998.085147,2020-01-02 08:00:00

In [25]:
df[df.duplicated(['time'])]

Empty DataFrame
Columns: [time, open_time, open, high, low, close, volume, close_time, quote_asset_volumne, number_of_trades, taker_buy_base_asset_volume, taker_buy_quote_asset_volume, ignore, formatted_open_time, formatted_close_time, upper_shadow, lower_shadow, real_body, CDLINVERTEDHAMMER, CDLHAMMER, CDLPIERCING, CDLMORNINGSTAR, CDLSHOOTINGSTAR, CDLHANGINGMAN, CDLDARKCLOUDCOVER, CDLEVENINGSTAR, CDLENGULFING, CDLENGULFINGBULLISH, CDLENGULFINGBEARISH, CDLINVERTEDHAMMER_NEW, CDLHAMMER_NEW, CDLPIERCING_NEW, CDLMORNINGSTAR_NEW, CDLENGULFINGBULLISH_NEW, CDLSHOOTINGSTAR_NEW, CDLHANGINGMAN_NEW, CDLDARKCLOUDCOVER_NEW, CDLEVENINGSTAR_NEW, CDLENGULFINGBEARISH_NEW, MA5, MA10, MA20, MA60, MA120, volume_MA5, volume_MA10, volume_MA20, SMA5, SMA10, SMA20, SMA60, SMA120, volume_SMA5, volume_SMA10, volume_SMA20, WMA5, WMA10, WMA20, WMA60, WMA120, volume_WMA5, volume_WMA10, volume_WMA20, EMA5, EMA10, EMA20, EMA60, EMA120, volume_EMA5, volume_EMA10, volume_EMA20, WILLR_14, NATR_14, PPO_12_26, CCI_14, ADX_14, ADXR_14, MACD_12_26_9, RSI_14, BBANDS_U, BBANDS_M, BBANDS_L, AD, ATR, HT_DC, SAR, ratio_high_open, ratio_low_open, ratio_close_open, time_to_chart_return, crypto_index, datetime]
Index: []

[0 rows x 92 columns]

In [24]:
df = df.drop_duplicates('time')

In [26]:
export_path = "../data"
export_filename = 'binance_BTCUSDT_15m_from_2020_01_01_to_2021_12_31_candlesticks_signals_processed_technical_indicators_and_crypto_index_v2'
export_extension = ".csv"
full_export_path = os.path.join(export_path, export_filename + export_extension)

In [27]:
df.to_csv(full_export_path, index=False)