# Add Log OHLC

In [118]:
import pandas as pd
import numpy as np
import datetime
import os

### Parameters

In [119]:
asset_ticket = "BTCUSDT"
timestamp = "1d"
start_date = "1 Jan, 2017"
end_date = "31 Dec, 2022"

In [120]:
input_data_path = '../../data/40_crypto_index'
input_data_filename = "binance" + \
                  "_" + asset_ticket + \
                  "_" + timestamp + \
                  "_from_" + datetime.datetime.strptime(start_date,'%d %b, %Y').strftime('%Y_%m_%d') + \
                  "_to_" + datetime.datetime.strptime(end_date,'%d %b, %Y').strftime('%Y_%m_%d') + \
                  "_candlesticks_signals_processed_technical_indicators_and_crypto_index"
input_data_extension = ".csv"

full_path_input_data = os.path.join(input_data_path, input_data_filename + input_data_extension)

In [121]:
df = pd.read_csv(full_path_input_data)

In [122]:
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,...,BBANDS_L,AD,ATR,HT_DC,SAR,ratio_high_open,ratio_low_open,ratio_close_open,time_to_chart_return,crypto_index
0,1513296000000,16334.98,17991.00,16298.45,17539.83,9181.273947,1513382399999,1.598097e+08,85478,4712.578400,...,7379.002668,89965.427218,1578.796612,27.561481,12668.038416,1.101379,0.997764,1.073759,0.073759,1073.758890
1,1513382400000,17516.81,19539.00,17190.01,19102.66,4202.628709,1513468799999,7.629372e+07,51777,2308.847163,...,7630.672196,92606.725304,1633.810425,27.275392,12880.956879,1.115443,0.981344,1.090533,0.089102,1169.432714
2,1513468800000,19120.19,19798.68,18510.00,18860.02,9177.183434,1513555199999,1.758674e+08,84581,4197.960835,...,7973.168363,88414.794602,1609.158252,27.027934,13280.439467,1.035486,0.968087,0.986393,-0.012702,1154.578702
3,1513555200000,18860.04,19300.00,17029.98,18856.25,10624.633071,1513641599999,1.963392e+08,91956,4690.302146,...,8404.835826,94885.560372,1656.362662,26.783773,13801.898709,1.023328,0.902966,0.999799,-0.000200,1154.347909
4,1513641600000,18856.25,18950.00,16300.00,17295.20,13210.748220,1513727999999,2.327906e+08,116569,5740.506184,...,9101.451223,91597.330362,1727.336758,26.580387,14281.641213,1.004972,0.864435,0.917213,-0.082787,1058.783053

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1842 entries, 0 to 1841
Data columns (total 91 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   open_time                     1842 non-null   int64
 1   open                          1842 non-null   float64
 2   high                          1842 non-null   float64
 3   low                           1842 non-null   float64
 4   close                         1842 non-null   float64
 5   volume                        1842 non-null   float64
 6   close_time                    1842 non-null   int64
 7   quote_asset_volume            1842 non-null   float64
 8   number_of_trades              1842 non-null   int64
 9   taker_buy_base_asset_volume   1842 non-null   float64
 10  taker_buy_quote_asset_volume  1842 non-null   float64
 11  ignore                        1842 non-null   int64
 12  formatted_open_time           1842 non-null   object
 13  formatted_close_time          1842 non-null   object
 14  date                          1842 non-null   object
 15  upper_shadow                  1842 non-null   float64
 16  lower_shadow                  1842 non-null   float64
 17  real_body                     1842 non-null   float64
 18  CDLINVERTEDHAMMER             1842 non-null   int64
 19  CDLHAMMER                     1842 non-null   int64
 20  CDLPIERCING                   1842 non-null   int64
 21  CDLMORNINGSTAR                1842 non-null   int64
 22  CDLSHOOTINGSTAR               1842 non-null   int64
 23  CDLHANGINGMAN                 1842 non-null   int64
 24  CDLDARKCLOUDCOVER             1842 non-null   int64
 25  CDLEVENINGSTAR                1842 non-null   int64
 26  CDLENGULFING                  1842 non-null   int64
 27  CDLENGULFINGBULLISH           1842 non-null   int64
 28  CDLENGULFINGBEARISH           1842 non-null   int64
 29  CDLINVERTEDHAMMER_NEW         1842 non-null   int64
 30  CDLHAMMER_NEW                 1842 non-null   float64
 31  CDLPIERCING_NEW               1842 non-null   int64
 32  CDLMORNINGSTAR_NEW            1842 non-null   int64
 33  CDLENGULFINGBULLISH_NEW       1842 non-null   float64
 34  CDLSHOOTINGSTAR_NEW           1842 non-null   int64
 35  CDLHANGINGMAN_NEW             1842 non-null   float64
 36  CDLDARKCLOUDCOVER_NEW         1842 non-null   int64
 37  CDLEVENINGSTAR_NEW            1842 non-null   float64
 38  CDLENGULFINGBEARISH_NEW       1842 non-null   float64
 39  MA5                           1842 non-null   float64
 40  MA10                          1842 non-null   float64
 41  MA20                          1842 non-null   float64
 42  MA60                          1842 non-null   float64
 43  MA120                         1842 non-null   float64
 44  volume_MA5                    1842 non-null   float64
 45  volume_MA10                   1842 non-null   float64
 46  volume_MA20                   1842 non-null   float64
 47  SMA5                          1842 non-null   float64
 48  SMA10                         1842 non-null   float64
 49  SMA20                         1842 non-null   float64
 50  SMA60                         1842 non-null   float64
 51  SMA120                        1842 non-null   float64
 52  volume_SMA5                   1842 non-null   float64
 53  volume_SMA10                  1842 non-null   float64
 54  volume_SMA20                  1842 non-null   float64
 55  WMA5                          1842 non-null   float64
 56  WMA10                         1842 non-null   float64
 57  WMA20                         1842 non-null   float64
 58  WMA60                         1842 non-null   float64
 59  WMA120                        1842 non-null   float64
 60  volume_WMA5                   1842 non-null   float64
 61  volume_WMA10                  1842 non-null   float64
 62  volume_WMA20                  1842 non-null   float64
 63  EMA5                          1842 non-null   float64
 64  EMA10                         1842 non-null   float64
 65  EMA20                         1842 non-null   float64
 66  EMA60                         1842 non-null   float64
 67  EMA120                        1842 non-null   float64
 68  volume_EMA5                   1842 non-null   float64
 69  volume_EMA10                  1842 non-null   float64
 70  volume_EMA20                  1842 non-null   float64
 71  WILLR_14                      1842 non-null   float64
 72  NATR_14                       1842 non-null   float64
 73  PPO_12_26                     1842 non-null   float64
 74  CCI_14                        1842 non-null   float64
 75  ADX_14                        1842 non-null   float64
 76  ADXR_14                       1842 non-null   float64
 77  MACD_12_26_9                  1842 non-null   float64
 78  RSI_14                        1842 non-null   float64
 79  BBANDS_U                      1842 non-null   float64
 80  BBANDS_M                      1842 non-null   float64
 81  BBANDS_L                      1842 non-null   float64
 82  AD                            1842 non-null   float64
 83  ATR                           1842 non-null   float64
 84  HT_DC                         1842 non-null   float64
 85  SAR                           1842 non-null   float64
 86  ratio_high_open               1842 non-null   float64
 87  ratio_low_open                1842 non-null   float64
 88  ratio_close_open              1842 non-null   float64
 89  time_to_chart_return          1842 non-null   float64
 90  crypto_index                  1842 non-null   float64
dtypes: float64(68), int64(20), object(3)
memory usage: 1.3+ MB

### Set the index on the dataframe

In [124]:
# Set the index on the dataframe
df['date_index'] = df['date']
df.set_index('date_index', inplace=True)

### Add log OHLC

In [125]:
df['log_open'] = np.log(df['open'])
df['log_high'] = np.log(df['high'])
df['log_low'] = np.log(df['low'])
df['log_close'] = np.log(df['close'])

In [126]:
df.shape

(1842, 95)

In [127]:
#Drop all Not a number values using drop method.
df.dropna(inplace = True)

In [128]:
df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,...,SAR,ratio_high_open,ratio_low_open,ratio_close_open,time_to_chart_return,crypto_index,log_open,log_high,log_low,log_close
date_index,,,,,,,,,,,,,,,,,,,,,
2017-12-16 00:00:00,1513296000000,16334.98,17991.00,16298.45,17539.83,9181.273947,1513382399999,1.598097e+08,85478,4712.578400,...,12668.038416,1.101379,0.997764,1.073759,0.073759,1073.758890,9.701064,9.797627,9.698825,9.772230
2017-12-17 00:00:00,1513382400000,17516.81,19539.00,17190.01,19102.66,4202.628709,1513468799999,7.629372e+07,51777,2308.847163,...,12880.956879,1.115443,0.981344,1.090533,0.089102,1169.432714,9.770916,9.880168,9.752084,9.857583
2017-12-18 00:00:00,1513468800000,19120.19,19798.68,18510.00,18860.02,9177.183434,1513555199999,1.758674e+08,84581,4197.960835,...,13280.439467,1.035486,0.968087,0.986393,-0.012702,1154.578702,9.858500,9.893371,9.826066,9.844800
2017-12-19 00:00:00,1513555200000,18860.04,19300.00,17029.98,18856.25,10624.633071,1513641599999,1.963392e+08,91956,4690.302146,...,13801.898709,1.023328,0.902966,0.999799,-0.000200,1154.347909,9.844801,9.867860,9.742731,9.844600
2017-12-20 00:00:00,1513641600000,18856.25,18950.00,16300.00,17295.20,13210.748220,1513727999999,2.327906e+08,116569,5740.506184,...,14281.641213,1.004972,0.864435,0.917213,-0.082787,1058.783053,9.844600,9.849559,9.698920,9.758184

## Export the Data

### Export parameters

In [129]:
export_path = "../../data/50_log"
export_filename = "binance" + \
                  "_" + asset_ticket + \
                  "_" + timestamp + \
                  "_from_" + datetime.datetime.strptime(start_date,'%d %b, %Y').strftime('%Y_%m_%d') + \
                  "_to_" + datetime.datetime.strptime(end_date,'%d %b, %Y').strftime('%Y_%m_%d') + \
                  "_candlesticks_signals_processed_technical_indicators_and_crypto_index_log"
export_extension = ".csv"
full_export_path = os.path.join(export_path, export_filename + export_extension)

### Export

In [130]:
df.to_csv(full_export_path, index=False)